Repository pahud/cdk-kaniko, pull requests merged in 2021-12, with the labels that each got.

#63 chore: Update typo in README.md
  README.md
Labels: stale

#65 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-merge, auto-approve

#66 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-merge, auto-approve

#67 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-merge, auto-approve

#68 chore(deps): upgrade dependencies
  .gitattributes
  .gitignore
  .projen/files.json
  package.json
  yarn.lock
Labels: auto-merge, auto-approve

#69 chore: bump cdkv2
  .gitattributes
  .github/workflows/release-cdkv1.yml
  .github/workflows/upgrade-cdkv1.yml
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.js
  README.md
  package.json
  test/__snapshots__/integ.default.test.ts.snap
  test/integ.default.test.ts
  yarn.lock
Labels: auto-approve
